### PR TITLE
Add missing translations

### PR DESCRIPTION
**Pull request by LordHansolo**

### CODE REVIEW

**Comment by legendhorus** [comment]
I see you have removed double quotes in many words.
For example:
The line when not edited: **"Close","Kapat",module,Magento_AdminNotification**
When edited: **Close, Kapat, module, Magento_AdminNotification**
This can make these words not translated anymore. Can you please tell me why you did that?

**Comment by LordHansolo** [comment]
Hello MyoDaisy,
Single words do not have to be in double quotes. We should only use double quotes in multi words phrases.

**Comment by legendhorus** [comment]
There is a lot of your data available in the original file. This leads to too much data, making it impossible for me to check it, so I can't merge it into the original file right now.
Can you send a contribution to us as a file containing only additional words and words to fix?
Thank you so much!

**Comment by LordHansolo** [comment]
Changes came from official Magento 2 Crowdin project. I see that tr_TR.csv was refreshed 4 months ago and since that on [Crowdin](https://crowdin.com/project/magento-2/tr) has been translated additional phrases. I understand that there can be a lot of changes and You have to check this all.  If You can't check changes that provide my pull request, can You provide the newest Crowdin translations to tr_TR.csv by Yourself?

**Comment by legendhorus** [comment]
We have updated the latest version from Crowdin. You can download and re-install the language pack.
Thank again for your contribution.

**Pull request closed without merging**
